Update to use Deno 1.18.2
Process function.ts
error: TS7022 [ERROR]: 'query' implicitly has type 'any' because it does
not have a type annotation and is referenced directly or indirectly in
its own initializer.

Process mod.ts
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules'
flag is provided requires using 'export type'.